table _medidas_
	lineageTag: dc5991f7-bfc9-4ee2-a80f-aa996b1b38c8

	measure 'Total Inadimplência' =
			CALCULATE(
			    SUM(fInadimplencia[VALOR_TITULO]),
			    fInadimplencia[status]="ATIVO"
			)
			
			// contratos novos e em renovação também estão em vigência
		formatString: #,0.00
		displayFolder: _inadimplência\_principais
		lineageTag: def00a3a-3fee-46fb-b238-6d08f05db056

	measure 'Qtd Cooperados Inadimplentes' =
			
			CALCULATE(DISTINCTCOUNT(fInadimplencia[PARENT]),
			fInadimplencia[status]="ATIVO"
			)
			
			// contratos novos e em renovação também estão em vigência
		formatString: #,0
		displayFolder: _inadimplência\_principais
		lineageTag: bfee6dfd-e087-4a5e-817f-52aec51ec9d1

	measure 'Qtd Conjuntos Inadimplentes' = ```
			
			CALCULATE(
			    DISTINCTCOUNT(fInadimplencia[id_conjunto]),
			    fInadimplencia[status]="ATIVO"
			)
			
			// contratos novos e em renovação também estão em vigência
			
			
			```
		formatString: #,0
		displayFolder: _inadimplência\_principais
		lineageTag: 407ba84c-1546-455d-8fd0-0e644c04a63c

	measure 'botão login' = ```
			
			IF(
			    SELECTEDVALUE('Login_senha_complementar (Login)'[Login]) = SELECTEDVALUE(Login_senha[Login]) &&
			    SELECTEDVALUE('Login_senha_complementar (Senha)'[Senha]) = SELECTEDVALUE(Login_senha[Senha]),
			    "Valores Inadimp","Senha Incorr.")
			
			
			
			
			            
			
			
			            
			
			    
			```
		lineageTag: 6a28e40f-e6dc-4cf7-ba0a-b09c128db5ad

	measure 'Conjuntos (%)' =
			
			DIVIDE(
			    [Qtd Conjuntos Inadimplentes],
			    [Total Conjuntos]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _inadimplência\_principais
		lineageTag: ac80408f-ad07-4b21-968c-29d2888c2d81

	measure 'Cooperados (%)' =
			
			DIVIDE([Qtd Cooperados Inadimplentes], [Total Cooperados])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _inadimplência\_principais
		lineageTag: a9555828-4566-43a9-9ec4-2024537b8720

	measure 'Ranking TopN' = ```
			
			IF(
			    ISINSCOPE(fInadimplencia[associado]),
			    RANKX(
			        ALL(fInadimplencia[associado]),
			        CALCULATE(SUM(fInadimplencia[valor_titulo])
			        )
			    )
			)
			// tive que usar CALCULATE pois ele estava pegando o valor total antes, então tudo dava 1 
			// daí o CALCULATE faz a transição de contexto linha a linha
			// na aula o léo faz com medida, mas toda medida tem um CALCULATE implícito)
			```
		formatString: 0
		displayFolder: _inadimplência
		lineageTag: 83f377c2-9310-4491-8d2a-4ab84dd31c71

	measure TopN =
			
			CALCULATE(
			    CALCULATE(SUM(fInadimplencia[valor_titulo])),
			    KEEPFILTERS(
			        TOPN(SELECTEDVALUE('TopN Table'[N], 5),
			        ALL(fInadimplencia[associado]),
			        CALCULATE(SUM(fInadimplencia[valor_titulo]))
			        )
			    )
			)
		formatString: #,0.00
		displayFolder: _inadimplência
		lineageTag: e88e4455-2c25-4fcb-a90d-82a769ada3bc

	measure 'Variação de Inadimplência' = ```
			
			VAR vILM = 
			CALCULATE(
			    [Total Inadimplência],
			    _dCalendario[Mes Counter] = MAX(_dCalendario[Mes Counter])-1
			)
			
			VAR vILMM = 
			CALCULATE(
			    [Total Inadimplência],
			    _dCalendario[Mes Counter] = MAX(_dCalendario[Mes Counter])-2
			)
			
			RETURN
			
			DIVIDE(vILM-vILMM, vILMM)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _inadimplência
		lineageTag: ae294031-84df-4092-9727-84604b384783

	measure 'Total Pagamentos' = ```
			
			    SUM(fPagamentos[valor_baixa])
			
			```
		displayFolder: _inadimplência\_principais
		lineageTag: ed10b9f3-d971-4d6b-a9ff-0a5d4b9863da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inadimplência (%)' =
			
			DIVIDE(
			    [Total Inadimplência],
			    [Total Valores]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _inadimplência\_principais
		lineageTag: e215deb3-152d-4275-ae06-2d1954dee6f7

	measure 'Total Valores' = [Total Pagamentos]+[Total Inadimplência]
		displayFolder: _inadimplência\_principais
		lineageTag: 2ad141c1-6d50-4062-90e1-496223d145e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Conjuntos' =
			
			CALCULATE(
			    DISTINCTCOUNT(fAtivos[id]),
			    ALL(_dCalendario)
			)
		formatString: #,0
		displayFolder: _inadimplência\_principais
		lineageTag: f27b4674-d1b7-44af-9b54-a7deb69dc859

	measure 'Total Cooperados' =
			CALCULATE(
			    DISTINCTCOUNT(fAtivos[matricula]),
			    ALL(_dCalendario)
			)
		formatString: #,0
		displayFolder: _inadimplência\_principais
		lineageTag: 1ec0a1b9-e45c-4e97-8a45-33bda2b8552d

	measure Inadimplência = SUM(fFaturas[valor_titulo])
		displayFolder: _inadimplência\_principais\historico
		lineageTag: 0752a0dc-461b-4c90-bfb9-bee56f7ab6bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quitação de Inadimp.' = SUM(fFaturas[valor_baixa])
		formatString: 0
		displayFolder: _inadimplência\_principais\historico
		lineageTag: a030e8b3-52b7-46eb-b773-3565b2470283

	measure '% Quitado' =
			DIVIDE(
			    [Quitação de Inadimp.],
			    [Inadimplência])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _inadimplência\_principais\historico
		lineageTag: baface00-1c5e-426d-8923-5a313fe93f52

	partition _medidas_ = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

